### ISSUE TITLE
DRAM Laptop - McStasScript running 

### ISSUE THREAD

**Issue by trnielsen** [ess-dmsc-dram/python-course-ikon#19]
* Make sure McStasScript is running on the DRAM laptop
* To be used for the introduction

**Comment by willend** [comment]
https://github.com/PaNOSC-ViNYL/McStasScript was checked out in the DRAM account homedir and a local jupyter notebook was run. Minimal changes in terms of setting up McStasscript to run with the installed McStas 2.6:

![Screenshot from 2020-02-07 11-23-31](https://user-images.githubusercontent.com/8593355/74021776-7bdc9180-499c-11ea-8100-83700211cb86.png)

The McStasScript_demo.ipynb ran successfully,  see below screenshots
![Screenshot from 2020-02-07 11-21-01](https://user-images.githubusercontent.com/8593355/74021653-3324d880-499c-11ea-8c33-79d53ec4d67d.png)

![Screenshot from 2020-02-07 11-21-15](https://user-images.githubusercontent.com/8593355/74021646-3029e800-499c-11ea-83cf-2e0c6fc058c9.png)

**Comment by trnielsen** [comment]
Seems to be running. Closing.
