### ISSUE TITLE
Working With Files

### ISSUE THREAD

**Issue by nvaytet** [ess-dmsc-dram/python-course-ikon#6]
Create a notebook for module titled "Working With Files"

**Comment by wpotrzebowski** [comment]
We have some of this in numpy tutorial but probably would be good to have some dedicated notebook too.

**Comment by nvaytet** [comment]
Yes, let's try to put something together with `readlines`, and formatting output. Also would probably be good to teach about the `with` context manager which should be used when opening files.

**Comment by wpotrzebowski** [comment]
I can try to compile something from these two: https://github.com/silx-kit/silx-training/blob/master/python/python/3_input_output.ipynb and https://www.mantidproject.org/Working_With_Files

**Comment by nvaytet** [comment]
@wpotrzebowski I’ve already made a start. See https://github.com/ess-dmsc-dram/python-course-ikon/tree/input_and_output?files=1

**Comment by nvaytet** [comment]
I’m basically just missing a coupe of exercises, if you have some ideas, just push to this branch

**Comment by nvaytet** [comment]
Fixed via #36
