### ISSUE TITLE
Installing Packages from conda and pypi

### ISSUE THREAD

**Issue by nvaytet** [ess-dmsc-dram/python-course-ikon#8]
Create a notebook for module titled "Installing Packages from conda and pypi"

**Comment by wpotrzebowski** [comment]
I can potentially add a few sentences about it to "using_modules" notebook

**Comment by nvaytet** [comment]
yes, good idea, just put a few things in there

**Comment by wpotrzebowski** [comment]
I've just added a simple description to using modules notebook
