### ISSUE TITLE
Using Modules

### ISSUE THREAD

**Issue by nvaytet** [ess-dmsc-dram/python-course-ikon#9]
Create a notebook for module titled "Using Modules"

**Comment by mads-bertelsen** [comment]
**Quick review of notebook**

In Exercise (2) it is never specified that the student should put the python file into the new folder.
Exercise (3) will just use the my module file that was uploaded originally, as the user was not told to remove it.

**Comment by wpotrzebowski** [comment]
Fixed notebook and solutions according to the comments in the review.
